In [2]:
import numpy as np
import cvxpy as cp 
%matplotlib inline
import matplotlib.pyplot as plt

In [3]:
x = cp.Variable()
y = cp.Variable()

In [4]:
constraints = [ x>= -1, x<= 1, y >= -1, y <= 1 ]

In [5]:
objective = cp.Minimize( x**2 + y**2)

In [6]:
problem = cp.Problem(objective, constraints)
solution = problem.solve()

In [7]:
print('Optimum value = ', solution)
print('Optimizer: ', x.value, y.value)

Optimum value =  0.0
Optimizer:  0.0 0.0


## Max flow on a graph

In [ ]:
# define variables
n = 4
X = cp.Variable((4,4))
# define constraints
C = np.array([[0,2,1,0],[2,0,1,1],[1,1,0,1],[0,1,1,0]])
constraints = [X>=0, X + cp.transpose(X) <= C, cp.sum(X[1:n-1,:],axis = 1)==cp.sum(cp.transpose(X)[1:n-1,:],axis=1), cp.sum(X[:,0])==0, cp.sum(X[n-1,:])==0]
# define objective
objective = cp.Maximize(cp.sum(X[0,:]))

In [9]:
problem = cp.Problem(objective, constraints)
solution = problem.solve()
print('Max flow = ',solution)
print('Optimizer = ',X.value)

Max flow =  2.000000000035156
Optimizer =  [[-1.11794888e-11  1.34157340e+00  6.58426602e-01  1.04779154e-11]
 [-8.64689711e-12  8.94734019e-14  5.02588193e-01  1.00000000e+00]
 [ 2.57433729e-11  1.61014795e-01  8.94734019e-14  1.00000000e+00]
 [-5.93137097e-12  5.87824662e-12 -5.68616735e-12  5.75960182e-12]]


In [10]:
problem = cp.Problem(objective, constraints)
solution = problem.solve()
print('Max flow = ',solution)
print('Optimizer = ',X.value)


Max flow =  2.000000000035156
Optimizer =  [[-1.11794888e-11  1.34157340e+00  6.58426602e-01  1.04779154e-11]
 [-8.64689711e-12  8.94734019e-14  5.02588193e-01  1.00000000e+00]
 [ 2.57433729e-11  1.61014795e-01  8.94734019e-14  1.00000000e+00]
 [-5.93137097e-12  5.87824662e-12 -5.68616735e-12  5.75960182e-12]]


## Maximum weight matching

In [6]:
W = np.array([[2,1,2.5],[3.1,2,3],[2.1,3,4.1]])
X = cp.Variable((3,3))
constraints = [X>=0, cp.sum(X,axis=0)==1, cp.sum(X,axis=1)==1]
probObjective = cp.Maximize(cp.sum(cp.multiply(W,X)))
problem = cp.Problem(probObjective, constraints)
solution = problem.solve()
print('Solution =', solution)
print(X.value)

Solution = 8.599999998745046
[[9.60270943e-10 7.95977926e-10 9.99999998e-01]
 [9.99999999e-01 7.42538910e-10 4.24040827e-10]
 [2.07006016e-10 9.99999998e-01 1.33217202e-09]]
