In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cvxpy as cp


In [5]:
X = np.random.rand(5,10)
Sigma = X@X.T 
eigvals,eigvecs = np.linalg.eig(Sigma)
print(eigvals)
Sigma = Sigma/np.max(eigvals)

eigvals,eigvecs = np.linalg.eig(Sigma)
print(Sigma)
print(eigvals)
print(eigvecs)

[12.18476792  1.66134376  0.1923024   0.50210844  0.84193743]
[[0.19810279 0.12615656 0.20191062 0.17480944 0.16728893]
 [0.12615656 0.17224379 0.15599562 0.15154404 0.17864052]
 [0.20191062 0.15599562 0.3142438  0.22749253 0.2434567 ]
 [0.17480944 0.15154404 0.22749253 0.21072216 0.18376669]
 [0.16728893 0.17864052 0.2434567  0.18376669 0.36712101]]
[1.         0.13634595 0.0157822  0.04120788 0.06909754]
[[-0.38822337 -0.37383843  0.19557461 -0.81789737 -0.04818629]
 [-0.34849519  0.07556114  0.39288212  0.27212031 -0.80276759]
 [-0.52101272 -0.29891359  0.38824661  0.44501663  0.5389074 ]
 [-0.4252783  -0.34603812 -0.79728462  0.17982086 -0.17719394]
 [-0.52489792  0.80339507 -0.14490006 -0.1631536   0.1772665 ]]


In [30]:
evec = eigvecs[:,0].reshape([5,1]) # evec is the eigenvector corresponding to the largest eigenvalue
E = evec @ evec.T
print((Sigma-np.eye(5))@ evec)
print(E)

[[-1.58885232e-16]
 [ 3.95317545e-16]
 [ 4.35474146e-16]
 [ 1.62493424e-16]
 [ 5.43441295e-16]]
[[0.15071738 0.13529398 0.20226931 0.16510297 0.20377764]
 [0.13529398 0.1214489  0.18157043 0.14820744 0.1829244 ]
 [0.20226931 0.18157043 0.27145426 0.2215754  0.2734785 ]
 [0.16510297 0.14820744 0.2215754  0.18086163 0.2232277 ]
 [0.20377764 0.1829244  0.2734785  0.2232277  0.27551783]]


In [29]:
V = cp.Variable([5,5],symmetric=True)
objective = cp.Maximize(cp.trace(Sigma.T@Sigma@V))
constraints = [cp.trace(V)==1, V>>0, np.eye(5)-V >>0]
problem  = cp.Problem(objective, constraints)
opt_val = problem.solve()
print(V.value)

[[0.1507174  0.13529397 0.20226928 0.16510294 0.20377768]
 [0.13529397 0.12144892 0.18157044 0.14820743 0.18292439]
 [0.20226928 0.18157044 0.27145427 0.22157537 0.27347852]
 [0.16510294 0.14820743 0.22157537 0.18086166 0.22322773]
 [0.20377768 0.18292439 0.27347852 0.22322773 0.27551775]]


In [31]:
E-V.value

array([[-1.76238092e-08,  3.29440447e-09,  3.01717849e-08,
         3.56757879e-08, -4.07959670e-08],
       [ 3.29440447e-09, -2.42015202e-08, -9.26417043e-09,
         1.37505884e-08,  1.81581694e-08],
       [ 3.01717849e-08, -9.26417043e-09, -1.16656571e-08,
         3.35054741e-08, -2.20560062e-08],
       [ 3.56757879e-08,  1.37505884e-08,  3.35054741e-08,
        -2.75313164e-08, -3.85693381e-08],
       [-4.07959670e-08,  1.81581694e-08, -2.20560062e-08,
        -3.85693381e-08,  8.10100936e-08]])